
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class AudioConfig : Luban.BeanBase
    {
        public AudioConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Path = _buf.ReadString();

            EndInit();
        }

        public static AudioConfig DeserializeAudioConfig(ByteBuf _buf)
        {
            return new AudioConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        public readonly string Path;
    
        public const int __ID__ = 1647377048;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Path:" + Path + ","
            + "}";
        }

        partial void EndRef();
    }

}

